/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIngestShoeEventRouteImport } from './routes/api/ingest/shoe-event'
import { Route as ApiPublicIngestShoeEventRouteImport } from './routes/api/public/ingest/shoe-event'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestShoeEventRoute = ApiIngestShoeEventRouteImport.update({
  id: '/api/ingest/shoe-event',
  path: '/api/ingest/shoe-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestShoeEventRoute =
  ApiPublicIngestShoeEventRouteImport.update({
    id: '/api/public/ingest/shoe-event',
    path: '/api/public/ingest/shoe-event',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ingest/shoe-event': typeof ApiIngestShoeEventRoute
  '/api/public/ingest/shoe-event': typeof ApiPublicIngestShoeEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ingest/shoe-event': typeof ApiIngestShoeEventRoute
  '/api/public/ingest/shoe-event': typeof ApiPublicIngestShoeEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ingest/shoe-event': typeof ApiIngestShoeEventRoute
  '/api/public/ingest/shoe-event': typeof ApiPublicIngestShoeEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ingest/shoe-event' | '/api/public/ingest/shoe-event'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ingest/shoe-event' | '/api/public/ingest/shoe-event'
  id:
    | '__root__'
    | '/'
    | '/api/ingest/shoe-event'
    | '/api/public/ingest/shoe-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiIngestShoeEventRoute: typeof ApiIngestShoeEventRoute
  ApiPublicIngestShoeEventRoute: typeof ApiPublicIngestShoeEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/shoe-event': {
      id: '/api/ingest/shoe-event'
      path: '/api/ingest/shoe-event'
      fullPath: '/api/ingest/shoe-event'
      preLoaderRoute: typeof ApiIngestShoeEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/shoe-event': {
      id: '/api/public/ingest/shoe-event'
      path: '/api/public/ingest/shoe-event'
      fullPath: '/api/public/ingest/shoe-event'
      preLoaderRoute: typeof ApiPublicIngestShoeEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiIngestShoeEventRoute: ApiIngestShoeEventRoute,
  ApiPublicIngestShoeEventRoute: ApiPublicIngestShoeEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
